image: python:3.9.18

stages:
  - test
  - build

test_waiter:
  stage: test
  script:
    - pip install poetry
    - poetry install
    - poetry run pytest

build_waiter:
  stage: build
  script:
    - pip install poetry
    - poetry build
    - ls dist
